Style
sharvashidze/positiveteam pull request #11
Opened 2021-12-21 18:47 UTC by AlexFilonenko88

2021-12-21 19:13 UTC, sharvashidze requested changes

2021-12-21 19:13 UTC, sharvashidze commented on src/sass/_contacts.scss
> +}
это можно удалить

2021-12-21 19:13 UTC, sharvashidze commented on src/sass/_contacts.scss
> +  @media screen and (min-width: 768px) {
это лишнее

2021-12-21 19:13 UTC, sharvashidze commented on src/sass/_contacts.scss
> +  @media screen and (min-width: 768px) {
@media

2021-12-21 19:13 UTC, sharvashidze commented on src/sass/main.css
> +li {
лишнее

2021-12-21 19:13 UTC, sharvashidze commented on src/sass/main.css
>  .example {
example где такое есть удали

2021-12-21 19:13 UTC, sharvashidze commented on src/sass/main.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
лишнее все у нас такого нет

2021-12-21 19:13 UTC, sharvashidze commented on src/sass/main.css
> +li {
короче сверху LI то что есть удали до  @charset "UTF-8";( это не трогаем )

2021-12-21 19:17 UTC, AlexFilonenko88 commented on src/sass/_contacts.scss
> +}
поправил

2021-12-21 19:18 UTC, AlexFilonenko88 commented on src/sass/_contacts.scss
> +  @media screen and (min-width: 768px) {
исправил

2021-12-21 19:18 UTC, AlexFilonenko88 commented on src/sass/main.css
> +li {
исправил

2021-12-21 19:23 UTC, sharvashidze requested changes

2021-12-21 19:23 UTC, sharvashidze commented on src/sass/main.css
скобки остались

2021-12-21 20:03 UTC, AlexFilonenko88 commented on src/sass/main.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
исправленно

2021-12-21 20:06 UTC, AlexFilonenko88 commented on src/sass/main.css
исправлено

2021-12-21 20:09 UTC, sharvashidze requested changes

2021-12-21 20:09 UTC, sharvashidze commented on src/sass/_example.scss
>  .example {
вес содержимое класса  .examle  надо было убрать

2021-12-21 20:11 UTC, AlexFilonenko88 commented on src/sass/_example.scss
>  .example {
исправил

2021-12-21 20:45 UTC, sharvashidze approved these changes

2021-12-21 20:46 UTC, sharvashidze approved these changes

2021-12-21 20:46 UTC, sharvashidze approved these changes

2021-12-21 20:46 UTC, sharvashidze approved these changes

2021-12-21 20:46 UTC, sharvashidze approved these changes

2021-12-21 20:46 UTC, sharvashidze approved these changes

2021-12-21 20:47 UTC, sharvashidze approved these changes

2021-12-21 20:47 UTC, sharvashidze approved these changes

2021-12-21 20:47 UTC, sharvashidze approved these changes

2021-12-21 20:47 UTC, sharvashidze approved these changes

2021-12-21 20:47 UTC, sharvashidze approved these changes

2021-12-21 20:48 UTC, sharvashidze approved these changes

2021-12-21 20:48 UTC, sharvashidze approved these changes

2021-12-21 20:48 UTC, sharvashidze approved these changes

2021-12-21 20:48 UTC, sharvashidze approved these changes

2021-12-21 20:49 UTC, sharvashidze approved these changes

2021-12-21 20:52 UTC, sharvashidze approved these changes

2021-12-21 20:52 UTC, sharvashidze approved these changes

2021-12-22 06:16 UTC, sharvashidze approved these changes

2021-12-22 06:16 UTC, sharvashidze approved these changes

2021-12-22 06:16 UTC, sharvashidze approved these changes

2021-12-22 06:30 UTC, sharvashidze approved these changes

2021-12-22 06:31 UTC, sharvashidze approved these changes

2021-12-22 06:54 UTC, closed without merging

2021-12-22 06:54 UTC, sharvashidze commented
не существует